# Write your SQL code for the database creation here. Good luck! 
CREATE DATABASE ShopDB;
USE ShopDB;

CREATE TABLE Products (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(50),
  Description VARCHAR(100),
  Price INT,
  WarehouseAmount INT
);


CREATE TABLE Customers(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  FirstName VARCHAR(50),
  LastName VARCHAR(100),
  Email VARCHAR(100),
  Address VARCHAR(50)
);


CREATE TABLE Orders(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  OrderID INT NULL,
  ProductID INT NULL
);

CREATE TABLE OrderItems (
ID INT AUTO_INCREMENT PRIMARY KEY,
OrderID INT NULL,
ProductID INT NULL,
FOREIGN KEY (OrderID) REFERENCES Orders(ID) ON DELETE SET NULL,
FOREIGN KEY (ProductID) REFERENCES Products(ID) ON DELETE SET NULL
);

